pipeline {
    agent any
    options {
        timeout(time: 10, unit: 'MINUTES')
    }
    parameters {
        string(name: 'GITHUB_CREDENTIAL', defaultValue: 'github_creds', description: 'Github access credentials id')
        string(name: 'GITHUB_REPO_URL', defaultValue: 'https://github.com/dkojo/springboot-app-cicd.git', description: 'Github repository url')
        string(name: 'GITHUB_BRANCH', defaultValue: 'main', description: 'Github branch for your build')
        string(name: 'SONARQUBE_SERVER_NAME', defaultValue: 'sonarqube_server', description: 'Name for your sonarqube server')
        string(name: 'NEXUS_URL', defaultValue: '3.85.111.212:8081', description: 'Your Nexus URL')
        string(name: 'NEXUS_CREDENTIAL', defaultValue: 'jenkins_nexus_creds', description: 'Your Nexus Credentials')
        string(name: 'REMOTE_USER', defaultValue: 'ec2-user', description: 'Remote server username')
        string(name: 'MONOLITHIC_SERVER', defaultValue: 'monolithic_server', description: 'The monolithic server that Jenkins will SSH into Using Publish Over SSH.')
    }

    environment {
        REMOTE_USER = "${params.REMOTE_USER}"
        GITHUB_CREDENTIAL = "${params.GITHUB_CREDENTIAL}"
        GITHUB_REPO_URL = "${params.GITHUB_REPO_URL}"
        GITHUB_BRANCH = "${params.GITHUB_BRANCH}"
        SONARQUBE_SERVER_NAME = "${params.SONARQUBE_SERVER_NAME}"
        NEXUS_URL = "${params.NEXUS_URL}"
        NEXUS_CREDENTIAL = "${params.NEXUS_CREDENTIAL}"
        MONOLITHIC_SERVER = "${params.MONOLITHIC_SERVER}"
    }

    stages {
        
        stage("Validate Parameters") {
            steps {
                script {
                    // Check if required parameters are provided
                    def requiredParameters = ['REMOTE_USER', 'GITHUB_CREDENTIAL', 'GITHUB_REPO_URL', 'GITHUB_BRANCH']
                    for (param in requiredParameters) {
                        if (!params.containsKey(param) || params[param].trim() == "") {
                            error("Parameter '$param' is missing or empty. Please provide a value.")
                        }
                    }
                }
            }
        }
        
        stage("Checkout Code From GitHub") {
            steps {
                script {
                    git branch: "${GITHUB_BRANCH}", credentialsId: "${GITHUB_CREDENTIAL}", url: "${GITHUB_REPO_URL}"
                }
            }
        }

        
        stage('Application Build And Test') {
            steps {
                sh 'chmod +x ./mvnw'
                sh './mvnw clean install'
                sh './mvnw test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withSonarQubeEnv("${SONARQUBE_SERVER_NAME}") {
                        sh './mvnw sonar:sonar'
                    }
                }
            }
        }
       
        stage('Upload Snapshot to Nexus Repository') {
            steps {
                script {
                  def nexusUrl = "${NEXUS_URL}"
                  def nexusCredentialsId = "${NEXUS_CREDENTIAL}"
                  def groupId = 'com.app'
                  def artifactId = 'blog'
                  def version = '0.0.1-SNAPSHOT'
                  def packaging = 'jar'

                  def artifactPath = "target/${artifactId}-${version}.${packaging}"

                nexusArtifactUploader(
                    nexusVersion: 'nexus3',
                    protocol: 'http',
                    nexusUrl: nexusUrl,
                    groupId: groupId,
                    version: version,
                    repository: 'maven-snapshots',
                    credentialsId: nexusCredentialsId,
                    artifacts: [
                        [artifactId: artifactId,
                         classifier: '',
                         file: artifactPath,
                         type: packaging,
                         filename: "${artifactId}-${version}.${packaging}"]
                    ]
                )
            }
        }
    }
        
        
        stage('Deploy To Monolithic Server') {
            steps {
                script {
                   def Command = '''
                       set -ex
                       cd ~/blog-app/
                # Check if any process is listening on port 8081 and kill it
                PID=$(/usr/sbin/lsof -t -i:8081)
                if [ -n "$PID" ]; then
                    kill $PID || true
                    echo "Killed process $PID"
                else
                    echo "No process found listening on port 8081"
                fi

                # Run the new jar file
                java -jar blog-0.0.1-SNAPSHOT.jar > logfile 2>&1 &
                echo "Started new blog application"
                sleep 7
                cat logfile
            '''

            sshPublisher(publishers: [sshPublisherDesc(
                configName: env.MONOLITHIC_SERVER,
                transfers: [sshTransfer(
                    sourceFiles: 'target/blog-0.0.1-SNAPSHOT.jar',
                    removePrefix: 'target/',
                    makeEmptyDirs: false,
                    remoteDirectory: '/blog-app/',
                    execCommand: Command,
                    execTimeout: 120000
                )],
                usePromotionTimestamp: false,
                useWorkspaceInPromotion: false,
                verbose: true,
            )])
        }
    }
}


    }
}
